# Generated by Django 3.1.7 on 2022-10-10 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221007_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 21, 10, 47, 838717)),
        ),
        migrations.CreateModel(
            name='DiscountSym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_discount', jsonfield.fields.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.store')),
            ],
        ),
    ]
